version: '3'
services:
  docker-basics-nodejs:
    build: .
    restart: on-failure
    volumes:
      - ./:/usr/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - docker-basics-postgres
    networks:
      - docker-basics-user-defined-bridge
  docker-basics-postgres:
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - docker-basics-user-defined-bridge

networks:
  docker-basics-user-defined-bridge:
    driver: bridge
