version: '3'
services:
  docker-basics-nodejs:
    build: .
    restart: on-failure
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - docker-basics-postgres
    command:
      [
        './wait.sh',
        'docker-basics-postgres:${POSTGRES_PORT}',
        '--',
        'npm',
        'run',
        'start-migration',
      ]
    networks:
      - docker-basics-user-defined-bridge
    environment:
      POSTGRES_HOST: docker-basics-postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
  docker-basics-postgres:
    build: ./database/
    volumes:
      - postgres-database-data:/var/logs
      - postgres-database-logs:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - docker-basics-user-defined-bridge

networks:
  docker-basics-user-defined-bridge:
    driver: bridge
volumes:
  postgres-database-data:
  postgres-database-logs:
